sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - 4
  - 6
  - 8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
